---
version: '2'
services:
  zookeeper-main:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper-maim
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22081:2181

  zookeeper-ext:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper-ext
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22082:2181
  
  kafka-alhpha:
    image: confluentinc/cp-kafka:latest
    container_name: kafka-alpha
    depends_on:
      - zookeeper-main
      - zookeeper-ext

    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-main:2181,zookeeper-ext:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-alpha:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  kafka-beta:
    image: confluentinc/cp-kafka:latest
    container_name: kafka-beta
    depends_on:
      - zookeeper-main
      - zookeeper-ext
    ports:
      - 29093:29093
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-main:2181,zookeeper-ext:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-beta:9092,PLAINTEXT_HOST://localhost:29093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "8080:8080"
    restart: always
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka-alpha:9092,kafka-beta:9092
      - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper-main:2181,zookeeper-ext:2181
      
  zipkin-server:
    image: openzipkin/zipkin:2
    container_name: zipkin-server
    ports:
      - 9411:9411
      
